image: node:10

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
    - npm install request
  artifacts:
    paths:
      - node_modules/

testing:
  stage: test
  script: 
    - npm start
    - npm test
